### ISSUE TITLE
无法渲染

### ISSUE THREAD

**Issue by ChrisGray0626** [Weic96/Hexo-Theme-Life#4]
`
{% extends 'includes/layout.swig' %} {% block body %}
{% include 'includes/recent-posts.swig' %} {% include 'includes/pagination.swig' %}
{% endblock %}
`

**Comment by yolilufei** [comment]
...
npm install hexo-renderer-swig --save

**Comment by yolilufei** [comment]
> `{% extends 'includes/layout.swig' %} {% block body %} {% include 'includes/recent-posts.swig' %} {% include 'includes/pagination.swig' %} {% endblock %}`

...
npm install hexo-renderer-swig --save
